DLL pull request
WildandArt/DoublyLinkedList pull request #1
Opened 2024-08-19 19:17 UTC by WildandArt

Impl of doubly linked list

2024-09-05 06:10 UTC, TalAharonSQream requested changes

2024-09-05 06:10 UTC, TalAharonSQream commented on README.md
Overview of the project before table of content. 
Whu java 22? is there a feature that you used that is only in java 22? java 17 users won't be able to compile the code with the javac 17? please verify that and fix the readme to be more generic about the Jave version the user needs. if the user already have jdk installed instruct him, how to move to a higher version if he needs. 


Explanation of the functions and methods is good but is looks a bit monotonic on the eyes so please make it colorful and use bold and different text sizes to emphasize every description and make space between one another.

YOu don't need to write about TDD, this is a method you use to develop you code but not relevant to the project description aka readme. no one cares how you wrote the test and in what way what they need to know that there are tests and that they are working and they can count on them. please add a description on how to run the tests.

2024-09-05 06:10 UTC, TalAharonSQream commented on pom.xml
make sure you have everything you need and no unnecessary things

2024-09-05 06:10 UTC, TalAharonSQream commented on src/main/java/com/DoublyLinkedList/App.java
> +        //with tests we won't need main function
Add a space "// text"

also i would just leave a comment empty and that's it no need to specify why

2024-09-05 06:10 UTC, TalAharonSQream commented on src/main/java/com/DoublyLinkedList/DoublyLinkedList.java
> +//  import com.DoublyLinkedList.Impl.NodeImpl;
remove if not used.

2024-09-05 06:10 UTC, TalAharonSQream commented on src/main/java/com/DoublyLinkedList/Impl/DoublyLinkedListImpl.java
The implementation looks good but there is a lot of if statements that in the eyes bother me. try to reduce the number of if statements while keeping the code work as expected and pass tests. there is a lot of methods on how to reduce if statements read about them.

2024-09-05 06:10 UTC, TalAharonSQream commented on src/main/java/com/DoublyLinkedList/Node.java
> +// package com.DoublyLinkedList;
remove unused comments from code

2024-09-08 07:23 UTC, WildandArt commented on README.md
compressed tdd talk to two lines. fixed to 17, it works with 17 too. put all method names inside code brackets, now its more pleasant to the eye

2024-09-08 07:24 UTC, WildandArt commented on src/main/java/com/DoublyLinkedList/App.java
> +        //with tests we won't need main function
fixed

2024-09-08 13:36 UTC, WildandArt commented on src/main/java/com/DoublyLinkedList/DoublyLinkedList.java
> +//  import com.DoublyLinkedList.Impl.NodeImpl;
ok

2024-09-08 13:36 UTC, WildandArt commented on src/main/java/com/DoublyLinkedList/Impl/DoublyLinkedListImpl.java
fixed, review again

2024-09-08 13:36 UTC, WildandArt commented on src/main/java/com/DoublyLinkedList/Node.java
> +// package com.DoublyLinkedList;
fixed

2024-09-10 07:57 UTC, YamtalDev commented on README.md
nice!

2024-09-10 07:59 UTC, YamtalDev approved these changes

2024-09-10 08:01 UTC, TalAharonSQream approved these changes

2024-09-12 11:19 UTC, WildandArt commented
Fixed version of DLL

2024-09-12 11:19 UTC, merged